name: release-assets

on:
  release:
    types: [created, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: node --version
      - run: yarn --version
      - run: yarn install
      - run: yarn build
      - run: echo "${{ github.event.release.tag_name }}" > dist/VERSION
      - run: echo "${{ github.sha }}" >> dist/VERSION
      - run: mv dist kadisoka-iam-webui
      - run: zip -r kadisoka-iam-webui.zip kadisoka-iam-webui
      - id: get_release
        uses: bruceadams/get-release@v1.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./kadisoka-iam-webui.zip
          asset_name: kadisoka-iam-webui-${{ github.event.release.tag_name }}.zip
          asset_content_type: application/zip
